name: "fastlivo2"
version: "0.1.0"
description: "FAST-LIVO2 is an efficient and accurate LiDAR-inertial-visual fusion localization and mapping system, demonstrating significant potential for real-time 3D reconstruction and onboard robotic localization in severely degraded environments."
maintainers:
  - name: "Ji Zhang"
    email: "zhangji@cmu.edu"
  - name: "fins"
    email: "fins@sjtu.edu.cn"
licenses:
  - "BSD"