name: "fastlivo2"
version: "0.1.0"
description: "FAST-LIVO2 is an efficient and accurate LiDAR-inertial-visual fusion localization and mapping system, demonstrating significant potential for real-time 3D reconstruction and onboard robotic localization in severely degraded environments."
maintainers:
  - name: "Ji Zhang"
    email: "zhangji@cmu.edu"
  - name: "fins"
    email: "fins@sjtu.edu.cn"
depends:
  Eigen3: "3.4.0"
  Sophus: "1.2.2"
  OpenMP: "system"
  
  geometry_msgs: "system"
  nav_msgs: "system"
  sensor_msgs: "system"
  cv_bridge: "system"
  pcl_conversions: "system"
  livox_ros_driver2: "system"

  PCL: "system"
  OpenCV: "system"
licenses:
  - "BSD"